# Site settings
title: Akarsh Galagali
email: akarshjg@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "I have experience working as a Pricing Marketing Engineer and Strategic Marketing Specialist. I have used Qlik Sense extensively to create apps and dashboards, incidentally I also used Qlik to automate few processes as well."
keywords: "Akarsh Galagali, Personal, data, analytics, Qlik, visualization, dashboard"
skills: "Marketing Specialist - Graphic Artist - User Experience Designer"
meta_author: Galagali Akarsh

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Akarsh

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Akarsh Galagali
  location: Bangalore
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/akarshgalagali/
  - title: twitter
    url: https://twitter.com/akarshgalagali
  - title: facebook
    url: https://www.facebook.com/akarshjg
  - title: stack-overflow
    url: https://stackoverflow.com/users/6458379/akarsh-galagali
  - title: instagram
    url: https://www.instagram.com/akarsh.galagali
  - title: github
    url: http://github.com/akarshjg

# Postal address (add as many lines as necessary)
address:
  - line: HSR Layout
  - line: Bengaluru, 560-102

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
